### ISSUE TITLE
DEBUG:: Monitor FPS and component lists

### ISSUE THREAD

**Issue by the-nightraven** [the-nightraven/01INT-AWG-SW#11]
## Task must include:
- [ ] A separate thread for debug tools
- [ ] Only available in debug build
- [ ] Start and kill thread on key press

## Keys:
- [ ] F3 -> enable/disable debug
- [ ] E -> show event/updater stacks
- [ ] R -> show renderer visible stack

**Comment by the-nightraven** [comment]
Renderer is the only thing that actually matters so its the only one implemented for now
